TEAMS = {
    'ana': {
        'country': 'US',
        'city': 'Anaheim',
        'short_name': 'Ducks',
        'long_name': 'Anaheim Ducks',
        'svg_light': 'https://assets.nhle.com/logos/nhl/svg/ANA_light.svg',
        'svg_dark' : 'https://assets.nhle.com/logos/nhl/svg/ANA_dark.svg',

    },
    'ari': {
        'country': 'US',
        'city': 'Arizona',
        'short_name': 'Coyotes',
        'long_name': 'Arizona Coyotes',
        'svg_light': 'https://assets.nhle.com/logos/nhl/svg/ARI_light.svg',
        'svg_dark' : 'https://assets.nhle.com/logos/nhl/svg/ARI_dark.svg',
    },
    'bos': {
        'country': 'US',
        'city': 'Boston',
        'short_name': 'Bruins',
        'long_name': 'Boston Bruins',
        'svg_light': 'https://assets.nhle.com/logos/nhl/svg/BOS_light.svg',
        'svg_dark' : 'https://assets.nhle.com/logos/nhl/svg/BOS_dark.svg',
    },
    'buf': {
        'country': 'US',
        'city': 'Buffalo',
        'short_name': 'Sabres',
        'long_name': 'Buffalo Sabres',
        'svg_light': 'https://assets.nhle.com/logos/nhl/svg/BUF_light.svg',
        'svg_dark' : 'https://assets.nhle.com/logos/nhl/svg/BUF_dark.svg',
    },
    'car': {
        'country': 'US',
        'city': 'Carolina',
        'short_name': 'Hurricanes',
        'long_name': 'Carolina Hurricanes',
        'svg_light': 'https://assets.nhle.com/logos/nhl/svg/CAR_light.svg',
        'svg_dark' : 'https://assets.nhle.com/logos/nhl/svg/CAR_dark.svg',
    },
    'cbj': {
        'country': 'US',
        'city': 'Columbus',
        'short_name': 'Blue Jackets',
        'long_name': 'Columbus Blue Jackets',
        'svg_light': 'https://assets.nhle.com/logos/nhl/svg/CBJ_light.svg',
        'svg_dark' : 'https://assets.nhle.com/logos/nhl/svg/CBJ_dark.svg',
    },
    'cgy': {
        'country': 'CA',
        'city': 'Calgary',
        'short_name': 'Flames',
        'long_name': 'Calgary Flames',
        'svg_light': 'https://assets.nhle.com/logos/nhl/svg/CGY_light.svg',
        'svg_dark' : 'https://assets.nhle.com/logos/nhl/svg/CGY_dark.svg',
    },
    'chi': {
        'country': 'US',
        'city': 'Chicago',
        'short_name': 'Blackhawks',
        'long_name': 'Chicago Blackhawks',
        'svg_light': 'https://assets.nhle.com/logos/nhl/svg/CHI_light.svg',
        'svg_dark' : 'https://assets.nhle.com/logos/nhl/svg/CHI_dark.svg',
    },
    'col': {
        'country': 'US',
        'city': 'Colorado',
        'short_name': 'Avalanche',
        'long_name': 'Colorado Avalanche',
        'svg_light': 'https://assets.nhle.com/logos/nhl/svg/COL_light.svg',
        'svg_dark' : 'https://assets.nhle.com/logos/nhl/svg/COL_dark.svg',
    },
    'dal': {
        'country': 'US',
        'city': 'Dallas',
        'short_name': 'Stars',
        'long_name': 'Dallas Stars',
        'svg_light': 'https://assets.nhle.com/logos/nhl/svg/DAL_light.svg',
        'svg_dark' : 'https://assets.nhle.com/logos/nhl/svg/DAL_dark.svg',
    },
    'det': {
        'country': 'US',
        'city': 'Detroit',
        'short_name': 'Red Wings',
        'long_name': 'Detroit Red Wings',
        'svg_light': 'https://assets.nhle.com/logos/nhl/svg/DET_light.svg',
        'svg_dark' : 'https://assets.nhle.com/logos/nhl/svg/DET_dark.svg',
    },
    'edm': {
        'country': 'CA',
        'city': 'Edmonton',
        'short_name': 'Oilers',
        'long_name': 'Edmonton Oilers',
        'svg_light': 'https://assets.nhle.com/logos/nhl/svg/EDM_light.svg',
        'svg_dark' : 'https://assets.nhle.com/logos/nhl/svg/EDM_dark.svg',
    },
    'fla': {
        'country': 'US',
        'city': 'Florida',
        'short_name': 'Panthers',
        'long_name': 'Florida Panthers',
        'svg_light': 'https://assets.nhle.com/logos/nhl/svg/FLA_light.svg',
        'svg_dark' : 'https://assets.nhle.com/logos/nhl/svg/FLA_dark.svg',
    },
    'lak': {
        'country': 'US',
        'city': 'Los Angeles',
        'short_name': 'Kings',
        'long_name': 'Los Angeles Kings',
        'svg_light': 'https://assets.nhle.com/logos/nhl/svg/LAK_light.svg',
        'svg_dark' : 'https://assets.nhle.com/logos/nhl/svg/LAK_dark.svg',
    },
    'min': {
        'country': 'US',
        'city': 'Minnesota',
        'short_name': 'Wild',
        'long_name': 'Minnesota Wild',
        'svg_light': 'https://assets.nhle.com/logos/nhl/svg/MIN_light.svg',
        'svg_dark' : 'https://assets.nhle.com/logos/nhl/svg/MIN_dark.svg',
    },
    'mtl': {
        'country': 'CA',
        'city': 'Montreal',
        'short_name': 'Canadiens',
        'long_name': 'Montreal Canadiens',
        'svg_light': 'https://assets.nhle.com/logos/nhl/svg/MTL_light.svg',
        'svg_dark' : 'https://assets.nhle.com/logos/nhl/svg/MTL_dark.svg',
    },
    'njd': {
        'country': 'US',
        'city': 'New Jersey',
        'short_name': 'Devils',
        'long_name': 'New Jersey Devils',
        'svg_light': 'https://assets.nhle.com/logos/nhl/svg/NJD_light.svg',
        'svg_dark' : 'https://assets.nhle.com/logos/nhl/svg/NJD_dark.svg',
    },
    'nsh': {
        'country': 'US',
        'city': 'Nashville',
        'short_name': 'Predators',
        'long_name': 'Nashville Predators',
        'svg_light': 'https://assets.nhle.com/logos/nhl/svg/NSH_light.svg',
        'svg_dark' : 'https://assets.nhle.com/logos/nhl/svg/NSH_dark.svg',
    },
    'nyi': {
        'country': 'US',
        'city': 'New York',
        'short_name': 'Islanders',
        'long_name': 'New York Islanders',
        'svg_light': 'https://assets.nhle.com/logos/nhl/svg/NYI_light.svg',
        'svg_dark' : 'https://assets.nhle.com/logos/nhl/svg/NYI_dark.svg',
    },
    'nyr': {
        'country': 'US',
        'city': 'New York',
        'short_name': 'Rangers',
        'long_name': 'New York Rangers',
        'svg_light': 'https://assets.nhle.com/logos/nhl/svg/NYR_light.svg',
        'svg_dark' : 'https://assets.nhle.com/logos/nhl/svg/NYR_dark.svg',
    },
    'ott': {
        'country': 'CA',
        'city': 'Ottawa',
        'short_name': 'Senators',
        'long_name': 'Ottawa Senators',
        'svg_light': 'https://assets.nhle.com/logos/nhl/svg/OTT_light.svg',
        'svg_dark' : 'https://assets.nhle.com/logos/nhl/svg/OTT_dark.svg',
    },
    'phi': {
        'country': 'US',
        'city': 'Philadelphia',
        'short_name': 'Flyers',
        'long_name': 'Philadelphia Flyers',
        'svg_light': 'https://assets.nhle.com/logos/nhl/svg/PHI_light.svg',
        'svg_dark' : 'https://assets.nhle.com/logos/nhl/svg/PHI_dark.svg',
    },
    'pit': {
        'country': 'US',
        'city': 'Pittsburgh',
        'short_name': 'Penguins',
        'long_name': 'Pittsburgh Penguins',
        'svg_light': 'https://assets.nhle.com/logos/nhl/svg/PIT_light.svg',
        'svg_dark' : 'https://assets.nhle.com/logos/nhl/svg/PIT_dark.svg',
    },
    'sea': {
        'country': 'US',
        'city': 'Seattle',
        'short_name': 'Kraken',
        'long_name': 'Seattle Kraken',
        'svg_light': 'https://assets.nhle.com/logos/nhl/svg/SEA_light.svg',
        'svg_dark' : 'https://assets.nhle.com/logos/nhl/svg/SEA_dark.svg',
    },
    'sjs': {
        'country': 'US',
        'city': 'San Jose',
        'short_name': 'Sharks',
        'long_name': 'San Jose Sharks',
        'svg_light': 'https://assets.nhle.com/logos/nhl/svg/SJS_light.svg',
        'svg_dark' : 'https://assets.nhle.com/logos/nhl/svg/SJS_dark.svg',
    },
    'stl': {
        'country': 'US',
        'city': 'St. Louis',
        'short_name': 'Blues',
        'long_name': 'St. Louis Blues',
        'svg_light': 'https://assets.nhle.com/logos/nhl/svg/STL_light.svg',
        'svg_dark' : 'https://assets.nhle.com/logos/nhl/svg/STL_dark.svg',
    },
    'tbl': {
        'country': 'US',
        'city': 'Tampa Bay',
        'short_name': 'Lightning',
        'long_name': 'Tampa Bay Lightning',
        'svg_light': 'https://assets.nhle.com/logos/nhl/svg/TBL_light.svg',
        'svg_dark' : 'https://assets.nhle.com/logos/nhl/svg/TBL_dark.svg',
    },
    'tor': {
        'country': 'CA',
        'city': 'Toronto',
        'short_name': 'Maple Leafs',
        'long_name': 'Toronto Maple Leafs',
        'svg_light': 'https://assets.nhle.com/logos/nhl/svg/TOR_light.svg',
        'svg_dark' : 'https://assets.nhle.com/logos/nhl/svg/TOR_dark.svg',
    },
    'van': {
        'country': 'CA',
        'city': 'Vancouver',
        'short_name': 'Canucks',
        'long_name': 'Vancouver Canucks',
        'svg_light': 'https://assets.nhle.com/logos/nhl/svg/VAN_light.svg',
        'svg_dark' : 'https://assets.nhle.com/logos/nhl/svg/VAN_dark.svg',
    },
    'vgk': {
        'country': 'US',
        'city': 'Vegas',
        'short_name': 'Golden Knights',
        'long_name': 'Vegas Golden Knights',
        'svg_light': 'https://assets.nhle.com/logos/nhl/svg/VGK_light.svg',
        'svg_dark' : 'https://assets.nhle.com/logos/nhl/svg/VGK_dark.svg',
    },
    'wpg': {
        'country': 'CA',
        'city': 'Winnipeg',
        'short_name': 'Jets',
        'long_name': 'Winnipeg Jets',
        'svg_light': 'https://assets.nhle.com/logos/nhl/svg/WPG_light.svg',
        'svg_dark' : 'https://assets.nhle.com/logos/nhl/svg/WPG_dark.svg',
    },
    'wsh': {
        'country': 'US',
        'city': 'Washington',
        'short_name': 'Capitals',
        'long_name': 'Washington Capitals',
        'svg_light': 'https://assets.nhle.com/logos/nhl/svg/WSH_light.svg',
        'svg_dark' : 'https://assets.nhle.com/logos/nhl/svg/WSH_dark.svg',
    },
}